Checkpoint Charlie.

diff --git a/test/data/www-dynamic/openshift/hooks/copy-scaffolding b/test/data/www-dynamic/openshift/hooks/copy-scaffolding
--- a/test/data/www-dynamic/openshift/hooks/copy-scaffolding
+++ b/test/data/www-dynamic/openshift/hooks/copy-scaffolding
@@ -25,44 +25,53 @@ declare -A  g_subst_map
 # Functions.
 #
 function init_substitution_map() {
-   cfg_dir="${1:-'.'}"
-   g_subst_map['www-dynamic:CONFIG_DIR']="${cfg_dir}"
+   local cfg_dir mapinfo
+   cfg_dir=${1:-'.'}
+   g_subst_map['www-dynamic:CONFIGURATION_DIR']="$cfg_dir"
+   g_subst_map['www-dynamic:BIND_ADDRESS']=`os_get_userifaddr`
 
    for k in `env | grep "^OPENSHIFT_" | cut -f1 -d '='`; do
       g_subst_map[$k]="${!k}"
    done
 
+   mapinfo="keys:[${!g_subst_map[@]}], values:[${g_subst_map[*]}]"
+   [ -n "$_DEBUG_HOOKS" ]  &&  os_debug_log "init_subst_map($1) = $mapinfo"
+   return 0
+
 }  #  End of function  init_substitution_map.
 
 
 function copy_template() {
+   local src dest
    src=${1:-""}
    dest=${2:-""}
  
-   [ ! -f "${src}" ]  &&  die 22 "copy_template - invalid source '${src}'"
-   [ -z "${dest}" ]   &&  die 22 "copy_template - invalid dest '${dest}'"
+   [ ! -f "$src" ]  &&  die 22 "copy_template - invalid source '$src'"
+   [ -z "$dest" ]   &&  die 22 "copy_template - invalid dest '$dest'"
 
    substitutions=""
-   for k in ${!g_subst_map[@]}"; do 
-      substitutions="s#\${$k}#${g_subst_map[$k]}#g;"
+   for k in ${!g_subst_map[@]}; do 
+      substitutions="$substitutions; s#\${$k}#${g_subst_map[$k]}#g;"
    done
 
-   sed "${substitutions}" "${src}" >  "${dest}"
+   sed "${substitutions}" "$src" >  "$dest"
 
 }  #  End of function  copy_template.
 
 
 function copy_scaffolding() {
-   config_dir="${1:-"."}/conf"
+   app_config_dir=${1:-"."}
 
    #  Ensure configuration exists for the component.
-   if ! test -d "${config_dir}"; then
-      mkdir -p "${config_dir}" "${config_dir}/../conf.d/"
+   if ! test -d "$app_config_dir/conf"; then
+      mkdir -p "$app_config_dir/conf" "$app_config_dir/conf.d/"
 
-      # Copy over the interpolated template to the app component space.
-      copy_template "../templates/httpd.conf"  "${config_dir}/httpd.conf"
-      copy_template "../templates/os-${openshift_profile}.conf"  \
-                    "${config_dir}/../conf.d/os-${openshift_profile}.conf"
+      local templates_dir
+      templates_dir=$(cd -P "${hook_dir}/../templates" && pwd -P)
+      for f in `(cd "$templates_dir"; find . -type f)`; do
+         # Copy over the interpolated template to the app component space.
+         copy_template "$templates_dir/$f" "$app_config_dir/$f"
+      done
    fi
 
 }  #  End of function  copy_scaffolding.
@@ -71,12 +80,13 @@ function copy_scaffolding() {
 #
 # _main()
 #
-source ./common.sh
+source $(cd -P -- "$(dirname -- "$0")" && pwd -P)/common.sh
 os_initialize_hook_env $@
-[ $# -eq 2 ]  ||  os_print_hook_usage
+[ $# -ge 1 ]  ||  os_print_hook_usage
 
-cfgdir="${OPENSHIFT_APP_PROD_DIR:-"."}/${app_config_subdir}/$component_guid"
-init_substitution_map "${cfgdir}"
-copy_scaffolding      "${cfgdir}"
+comp_guid=${OPENSHIFT_COMPONENT_GUID:-""}
+cfgdir=${OPENSHIFT_APP_PROD_DIR:-"."}/$app_config_subdir/$comp_guid
+init_substitution_map "$cfgdir"
+copy_scaffolding      "$cfgdir"
 
 
diff --git a/test/data/www-dynamic/openshift/hooks/start b/test/data/www-dynamic/openshift/hooks/start
--- a/test/data/www-dynamic/openshift/hooks/start
+++ b/test/data/www-dynamic/openshift/hooks/start
@@ -23,36 +23,35 @@ set -e
 #
 # _main()
 #
-source ./common.sh
-os_initialize_hook_env $@
-[ $# -eq 2 ]  ||  os_print_hook_usage
+source $(cd -P -- "$(dirname -- "$0")" && pwd -P)/common.sh
+os_initialize_hook_env "$@"
+[ $# -ge 1 ]  ||  os_print_hook_usage
 
-cfgdir="${OPENSHIFT_APP_PROD_DIR:-"."}/${app_config_subdir}/$component_guid/conf/"
+comp_guid=${OPENSHIFT_COMPONENT_GUID:-""}
+cfgdir=${OPENSHIFT_APP_PROD_DIR:-"."}/$app_config_subdir/$comp_guid
+cfgfile="$cfgdir/conf/httpd.conf"
 
-#  First up need to ensure configuration exists for the component.
-if ! test -f "${cfgdir}/httpd.conf"; then
-   echo "Error: Missing configuration file - ${cfgdir}/httpd.conf" 2>
-   exit 2
+#  Ensure configuration exists for the component.
+if ! test -f "$cfgfile"; then
+   die 2 "Missing configuration file - $cfgfile"
 fi
 
 
 #  Setup command line options.
-httpd_opts="-C 'Include ${cfgdir}/../conf.d/*.conf'"
+httpd_opts="-C 'Include $cfgdir/conf.d/*.conf'"
 
 if [ "X$hook_name" = "Xstart" ]; then
-   addrnport="$_OPENSHIFT_APP_BINDADDR:$_OPENSHIFT_APP_PORT"
-   httpd_opts="${httpd_opts} -C 'Listen $addrnport'"
-   httpd_opts="${httpd_opts} -C 'User  $_OPENSHIFT_APP_USER'"
-   httpd_opts="${httpd_opts} -C 'Group $_OPENSHIFT_APP_GROUP'"
+   user_name=`id -un`
+   group_name=`id -gn`
+   [ `id -u` -eq 0 ]  && user_name=apache  &&  group_name=apache
+
+   httpd_opts="${httpd_opts} -C 'User  $user_name"
+   httpd_opts="${httpd_opts} -C 'Group $group_name"
 fi
 
-prod_dir="${OPENSHIFT_APP_PROD_DIR:-"."}"
-var_run_dir="$prod_dir/var/run"
+rundir="${OPENSHIFT_APP_PROD_DIR:-"."}"
+[ -d "$rundir/var/run" ]  ||  mkdir -p "$rundir/var/run"
 
-[ -d "$var_run_dir" ]  ||  mkdir -p "$var_run_dir"
-
-cd "$prod_dir"
-/usr/sbin/httpd -f ${cfgdir}/httpd.conf ${httpd_opts} -k $hook_name
-
-logger -p user.notice  "$cartridge_name->$0 $@ + opts=${httpd_opts}"
+(cd "$rundir"; /usr/sbin/httpd -f $cfgfile $httpd_opts -k $hook_name)
+os_log_notice "$@ + opts=${httpd_opts}"
 exit 0
