Cleanup and fixes for variable names.

diff --git a/test/data/www-dynamic/openshift/hooks/start b/test/data/www-dynamic/openshift/hooks/start
--- a/test/data/www-dynamic/openshift/hooks/start
+++ b/test/data/www-dynamic/openshift/hooks/start
@@ -19,11 +19,13 @@
 # Exit on errors.
 set -e
 
+# Initialization.
 cartridge_name="www-dynamic.apache2"
-source ./common.sh
-
 hook_name=$(basename "$0")
 test $OPENSHIFT_TRACE_HOOKS && echo "!DEBUG! :$SHLVL: $hook_name $@"
+
+source ./common.sh
+
 
 #
 # _main()
@@ -32,21 +34,21 @@ os_check_args "$@"  ||  print_usage "Start www-dynamic.apache2 Component"
 
 app_guid=$1
 component_guid=$2
-declare -r platform_type=${OPENSHIFT_PLATFORM_TYPE:-"/express"}
+declare -r platform_type=${_OPENSHIFT_PLATFORM_TYPE:-"/express"}
 
-component_dir=${OPENSHIFT_COMPONENT_CONFIG_DIR:-"/tmp"}
-cart_cfgdir="${cartridge_name}/conf"
-cfgdir="${component_dir}/${cart_cfgdir}"
+cfgdir="${_OPENSHIFT_APP_CONFIG_DIR:-"/tmp"}/$comp_guid"
+cart_cfg_subdir="${cartridge_name}/conf"
+cloc="${cfgdir}/${cart_cfg_subdir}"
 
 #  First up need to ensure configuration exists for the component.
-if ! test -f "${cfgdir}/httpd.conf"; then
-   echo "Error: Missing configuration ${cart_cfgdir}/httpd.conf for component $component_guid" 2>
-   exit 255
+if ! test -f "${cloc}/httpd.conf"; then
+   echo "Error: Missing configuration file - ${cloc}/httpd.conf" 2>
+   exit 2
 fi
 
 
 #  Setup command line options.
-httpd_opts="-C 'Include ${cartridge_name}/conf.d/*.conf'"
+httpd_opts="-C 'Include ${cfgdir}/${cartridge_name}/conf.d/*.conf'"
 
 if [ "X$hook_name" = "Xstart" ]; then
    addrnport="$_OPENSHIFT_APP_BINDADDR:$_OPENSHIFT_APP_PORT"
@@ -57,4 +59,4 @@ fi
 
 /usr/sbin/httpd -f ${cfgdir}/httpd.conf ${httpd_opts} -k $hook_name
 
-logger -p user.notice  "www-dynamic.apache2: $0 $@  + opts=${httpd_opts}"
+logger -p user.notice  "www-dynamic.apache2: $0 $@ + opts=${httpd_opts}"
