Changes to www-dynamic cart.

diff --git a/test/data/www-dynamic/openshift/connectors/set_doc_root b/test/data/www-dynamic/openshift/connectors/set_doc_root
--- a/test/data/www-dynamic/openshift/connectors/set_doc_root
+++ b/test/data/www-dynamic/openshift/connectors/set_doc_root
@@ -1,1 +1,56 @@
-./set_doc_root <connection id> <doc root> (eg:file:///srv/webapps/132423423433423432/app)
+#!/bin/bash
+#
+# Copyright © 2010 Red Hat, Inc. All rights reserved
+#
+# This copyrighted material is made available to anyone wishing to use, modify,
+# copy, or redistribute it subject to the terms and conditions of the GNU
+# General Public License v.2.  This program is distributed in the hope that it
+# will be useful, but WITHOUT ANY WARRANTY expressed or implied, including the
+# implied warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
+# See the GNU General Public License for more details.  You should have
+# received a copy of the GNU General Public License along with this program;
+# if not, write to the Free Software Foundation, Inc., 51 Franklin Street,
+# Fifth Floor, Boston, MA 02110-1301, USA. Any Red Hat trademarks that are
+# incorporated in the source code or documentation are not subject to the GNU
+# General Public License and may only be used or replicated with the express
+# permission of Red Hat, Inc.
+#
+
+# Exit on errors.
+set -e
+
+#
+# _initialize()
+#
+cartridge_name="www-dynamic"
+script=$(basename "$0")
+[ -n "$_TRACE_HOOKS" ] && set -x
+[ -n "$_TRACE_HOOKS" ] && echo "!TRACE! :$SHLVL: $cartridge_name->$script $@"
+parameter_info="<application-guid> <component-guid> <connection-id> <doc-root>"
+
+
+#
+# _main()
+#
+source ../hooks/common.sh
+os_initialize_hook_env "${_OPENSHIFT_APP_CONFIG_DIR}"
+[ $# -eq 4 ]  ||  die 1 "Usage: $cartridge_name->$script ${parameter_info}"
+
+# ./set_doc_root <app_guid> <comp_guid> <connection id> <doc root>
+# (eg:file:///srv/webapps/132423423433423432/app)
+
+# Parameter values.
+app_guid=$1
+comp_guid=$2
+
+cfgdir="${_OPENSHIFT_APP_CONFIG_DIR:-'.'}/$comp_guid"
+
+#  Replace document root in any/all config files.
+for d in conf conf.d; do
+   for f in `ls "${cfgdir}/$cartridge_name/$d"`; do
+      sed -i "s#\(\s*DocumentRoot[ \t]\)\(.*\)\$#\1 $3 #"   \
+                "${cfgdir}/$cartridge_name/$d/$f"
+   done
+done
+
+exit 0
diff --git a/test/data/www-dynamic/openshift/hooks/start b/test/data/www-dynamic/openshift/hooks/start
--- a/test/data/www-dynamic/openshift/hooks/start
+++ b/test/data/www-dynamic/openshift/hooks/start
@@ -19,36 +19,25 @@
 # Exit on errors.
 set -e
 
-# Initialization.
-cartridge_name="www-dynamic.apache2"
-hook_name=$(basename "$0")
-test $OPENSHIFT_TRACE_HOOKS && echo "!DEBUG! :$SHLVL: $hook_name $@"
-
-source ./common.sh
-
 
 #
 # _main()
 #
-os_check_args "$@"  ||  print_usage "Start www-dynamic.apache2 Component"
+source ./common.sh
+os_initialize_hook_env $@
+[ $# -eq 2 ]  ||  os_print_hook_usage
 
-app_guid=$1
-component_guid=$2
-declare -r platform_type=${_OPENSHIFT_PLATFORM_TYPE:-"/express"}
-
-cfgdir="${_OPENSHIFT_APP_CONFIG_DIR:-"/tmp"}/$comp_guid"
-cart_cfg_subdir="${cartridge_name}/conf"
-cloc="${cfgdir}/${cart_cfg_subdir}"
+cfgdir="${OPENSHIFT_APP_PROD_DIR:-"."}/${app_config_subdir}/$component_guid/conf/"
 
 #  First up need to ensure configuration exists for the component.
-if ! test -f "${cloc}/httpd.conf"; then
-   echo "Error: Missing configuration file - ${cloc}/httpd.conf" 2>
+if ! test -f "${cfgdir}/httpd.conf"; then
+   echo "Error: Missing configuration file - ${cfgdir}/httpd.conf" 2>
    exit 2
 fi
 
 
 #  Setup command line options.
-httpd_opts="-C 'Include ${cfgdir}/${cartridge_name}/conf.d/*.conf'"
+httpd_opts="-C 'Include ${cfgdir}/../conf.d/*.conf'"
 
 if [ "X$hook_name" = "Xstart" ]; then
    addrnport="$_OPENSHIFT_APP_BINDADDR:$_OPENSHIFT_APP_PORT"
@@ -57,6 +46,13 @@ if [ "X$hook_name" = "Xstart" ]; then
    httpd_opts="${httpd_opts} -C 'Group $_OPENSHIFT_APP_GROUP'"
 fi
 
+prod_dir="${OPENSHIFT_APP_PROD_DIR:-"."}"
+var_run_dir="$prod_dir/var/run"
+
+[ -d "$var_run_dir" ]  ||  mkdir -p "$var_run_dir"
+
+cd "$prod_dir"
 /usr/sbin/httpd -f ${cfgdir}/httpd.conf ${httpd_opts} -k $hook_name
 
-logger -p user.notice  "www-dynamic.apache2: $0 $@ + opts=${httpd_opts}"
+logger -p user.notice  "$cartridge_name->$0 $@ + opts=${httpd_opts}"
+exit 0
